### ISSUE TITLE
Descriptions after Kings Pawn Game 1. e4,  and 1. e4 e5 are identical

### ISSUE THREAD

**Issue by dragunovartem99** [lichess-org/chess-openings#123]
We have a problem: incorrect description on the 1. e4 page

https://lichess.org/opening/Kings_Pawn_Game
<img width="600" alt="Screenshot 2023-04-22 at 14 19 35" src="https://user-images.githubusercontent.com/79096629/233781165-599ac73b-c50f-4754-91a2-1a3623ad5315.png">

https://lichess.org/opening/Kings_Pawn_Game/e4
<img width="600" alt="Screenshot 2023-04-22 at 14 19 54" src="https://user-images.githubusercontent.com/79096629/233781179-4837de36-5766-4347-9cd1-cc899c0ef1a3.png">

https://lichess.org/opening/Kings_Pawn_Game/e4_e5
<img width="600" alt="Screenshot 2023-04-22 at 14 15 06" src="https://user-images.githubusercontent.com/79096629/233780954-e936c7bf-6996-4424-9763-4a4230076a15.png">

**Comment by TBestLittleHelper** [comment]
Fixed by applying the  "- e5:"  tag that had been forgotten. This is an editor mistake, so no code change needed.

**Comment by niklasf** [comment]
Oh, Til that's a thing. Thanks!
