### ISSUE TITLE
Change the "gunderam defense" name to "Brazilian defense"

### ISSUE THREAD

**Issue by CodingNix** [lichess-org/chess-openings#142]
After suggesting the idea in discord it was suggested for me to open an issue here. 

https://en.wikipedia.org/wiki/Gunderam_Defense

Although its known as gunderam defense, the first one to play it was Hélder Câmara, 4 years before. Also known as the brazilian defense, i think it would be a nice name to have since there is no openings with the Brazil name.

**Comment by niklasf** [comment]
Asked for opinions internally. No consensus to change, but some even older instances:

```
[Event "Gothenburg-C"]
[Site "Gothenburg"]
[Date "1920.08.07"]
[Round "5"]
[White "Jensen, TC."]
[Black "Krenzisky, Simon"]
[Result "1/2-1/2"]
[ECO "C40"]
[PlyCount "126"]
[EventDate "1920.??.??"]
[EventType "tourn"]
[EventRounds "13"]
[EventCountry "SWE"]
[Source "ChessBase"]
[SourceDate "1999.11.16"]

{ ... }

[Event "YUG-ch"]
[Site "Belgrade"]
[Date "1948.??.??"]
[Round "12"]
[White "Fuderer, Andrija"]
[Black "Puc, Stojan"]
[Result "1-0"]
[ECO "C40"]
[PlyCount "73"]
[EventDate "1948.??.??"]
[EventType "tourn"]
[EventRounds "17"]
[EventCountry "YUG"]
[Source "ChessBase"]
[SourceDate "1999.11.16"]

{ ... }
```

So I guess we'll stay with the first publication rather than the first time played.
