### ISSUE TITLE
French Advance: Milner-Barry Gambit and Sørensen Gambit

### ISSUE THREAD

**Issue by seccohazy** [lichess-org/chess-openings#200]
`1. e4 e6 2. d4 d5 3. e5 c5 4. c3 Nc6 5. Nf3 Qb6 6. Bd3 `
 
The Milner-Barry Gambit in the French Advance gambits a pawn on d4 for quick development. The opening explorer identifies 6.Bd3 as the gambit move, but this seems premature and somewhat inaccurate — White can avoid the gambit and hold on to the pawn on the next move. (For example 6...Bd7 7. dxc5, or alternatively 6... cxd4 7. cxd4 Bd7 8. Be2).

As I understand it, and as the books talk about it, White gives up the pawn with 7.O-O — or, if Black includes 6... cxd4 7. cxd4 Bd7, it begins with the move 8. O-O.
 
I'm not sure if the directory even allows for two separate positions being given the same name. In that case Milner-Barry at 6. Bd3 is probably fine.
 
In the same line, I would also like to see the inclusion of the "Sørensen Gambit". I've seen it mentioned in John Watson's _Play the French_ and in Viktor Moskalenko's _The Even More Flexible French_. It's this knight move—
 
`1. e4 e6 2. d4 d5 3. e5 c5 4. c3 Qb6 5. Nf3 Nc6 6. Bd3 cxd4 7. cxd4 Bd7 8. O-O Nxd4 9. Ng5`
 
Apologies for not attempting a pull request myself, thanks in advance for any help with this.

**Comment by esmith1092** [comment]
@seccohazy I opened a PR to add this line
