### ISSUE TITLE
Martian Gambit - no lichess.org/opening page.

### ISSUE THREAD

**Issue by TheForkPower** [lichess-org/chess-openings#207]
- I just added Martian Gambit to book, 
- 1. e4 c6 2. d4 d5 3. Nd2 dxe4 4. Nxe4 Bf5 5. Ng5 Bg6 6. N1f3 h6 7. Ne6 . 

When you put this into Lichess PGN, it shows in the Opening Book that there is an opening: B18 Caro-Kann Defence Martian Gambit, but when you press on the link [it takes you to an empty wrong page that doesn't follow the same URL structure as the Other opening pag](https://lichess.org/opening?q=Caro-Kann+Defense%3A+Martian+Gambit) , there is no page! I can't look at continuations on winrates like you do on other openings etc, like on [Alien Gambit](https://lichess.org/opening/Caro-Kann_Defense_Alien_Gambit/e4_c6_d4_d5_Nc3_dxe4_Nxe4_Nf6_Ng5_h6_Nxf7)

how to fix? Can somebody fix?

**Comment by niklasf** [comment]
That's probably due to:

> The changes will be live on lichess.org after the next update of [scalachess](https://github.com/lichess-org/scalachess) (no fixed schedule) and the [opening explorer](https://github.com/lichess-org/lila-openingexplorer) (daily).

The date of the last server update is listed on https://lichess.org/source, though it's not guaranteed that it always includes a scalachess update.
