### ISSUE TITLE
Halloween Gambit should be C47

### ISSUE THREAD

**Issue by rsarson** [lichess-org/chess-openings#30]
https://en.wikipedia.org/wiki/Halloween_Gambit

**Comment by niklasf** [comment]
Sounds plausible. I assume

> C46 Three Knights Game including Halloween Gambit

from https://en.wikipedia.org/wiki/List_of_chess_openings#C20%E2%80%93C99 is a mistake?

**Comment by rsarson** [comment]
That's one of the sites I've been studying from and it certainly isn't perfect, lol.  It's better than the ECO code index listed at https://en.wikibooks.org/wiki/Chess_Opening_Theory/ECO_volume_A (BCDE), though.  I'd be curious to see how all these sites compare to the actual printed volumes of the Encyclopaedia of Chess Openings (https://en.wikipedia.org/wiki/Encyclopaedia_of_Chess_Openings).

Anyway fwiw, my main source is the scid.eco file from http://scid.sourceforge.net/.  It seems to be the most dependable, imo.

**Comment by niklasf** [comment]
Ok, thanks. Fixed.

**Comment by rsarson** [comment]
I've noticed lichess isn't updated yet... roughly how long does it take for changes like this to be implemented?

**Comment by niklasf** [comment]
Thanks for the reminder. Usually we bundle patches like this with bigger changes before releasing, so it depends. I updated the opening explorer just now. For other parts of the site it can still take a while.
