### ISSUE TITLE
Rename KE7 variation in the Bongcloud Attack to "Zelensky Defence"

### ISSUE THREAD

**Issue by wechord** [lichess-org/chess-openings#32]
When KE2 is played and black replies with KE7, it should be known as the Zelensky Defence in light of Ukraine president's efforts to fight against russia

FEN: rnbq1bnr/ppppkppp/8/4p3/4P3/8/PPPPKPPP/RNBQ1BNR w - - 2 3

**Comment by Vasilisck** [comment]
Greatest idea of all times.

**Comment by MachineThing** [comment]
Zelenskyy has two ys FYI.

**Comment by niklasf** [comment]
I am not in favor, because this one can be misunderstood: A bad opening or at least brave/fair but stupid opening. Also the focus should be the Ukrainian people, not so much their president. Will raise it with the team regardless.

**Comment by wechord** [comment]
If this variation doesn't work then maybe we can find a more suitable one and if zelensky defence doesn't work maybe ukrainian defence is more suited. I do agree it's a bad opening but strong players like carlsen and gm's can still play very well which could be interpreted by the strong will of the president and the ukrainian people who are still fighting strong even when the odds are heavily against them.

In a philosophical sense the war is bad and it reflects the opening, both sides are in a bad position and are forced to fight

**Comment by niklasf** [comment]
[Our initial response](https://lichess.org/blog/Yie1MhIAACAAk6OQ/lichess-statement-on-the-war-in-ukraine) with more concrete actions to come, but not this one.
