### ISSUE TITLE
King's Gambit

### ISSUE THREAD

**Issue by ddugovic** [lichess-org/chess-openings#35]
> When I was analyzing the King's gambit in detail, I just realized that in the Opening Explorer, when you play 1.e4 e5 2.f4 exf4 3.Nf3 it says "King's gambit : King's Knight gambit" but when you play g5 it says "King's gambit : King Knight's gambit".

https://lichess.org/forum/lichess-feedback/kings-knight-gambit-vs-king-knights-gambit

I'm unsure which it is supposed to be.

**Comment by niklasf** [comment]
Wikipedia has a crossover: https://en.wikipedia.org/wiki/King%27s_Gambit#King's_Knight's_Gambit:_3.Nf3. Makes sense to me, so picking that.
