### ISSUE TITLE
Giuoco Piano and Italian Game

### ISSUE THREAD

**Issue by ulthiel** [lichess-org/chess-openings#56]
In the database the line "1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5" is called the "Giuoco Piano", which is correct I think. But then every other line continuing from there is called "Italian Game: ...". There's also "Italian Game: Giuoco Piano, ...". But then the first line above should also be named "Italian Game: Giuoco Piano". This seems to be somewhat inconsistent, or is there an explanation?

**Comment by ulthiel** [comment]
In the ECO database of SCID the line 1.e4 e5 2.Nf3 Nc6 3.Bc4 is called "Italian Game" and 1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 is called "Giuoco Piano" (which further distributes into Giuoco Piano, Giuco Pianissimo, and Evans Gambit). I find this quite consistent.

**Comment by niklasf** [comment]
I think the first suggestion (going with `Italian Game: Giuoco Piano`) ist most consistent. Do you want to submit a pull request?

**Comment by hitansh1299** [comment]
I see this issue is still open, I'll be submitting a PR shortly
