### ISSUE TITLE
Blackburne Shilling Kostić?

### ISSUE THREAD

**Issue by kubafast** [lichess-org/chess-openings#57]
Re naming of the below:

a) C50 Blackburne Shilling Gambit 1. e4 e5 2. Nf3 Nc6 3. Bc4 Nd4 4. Nxe5 Qg5 5. Nxf7 Qxg2 6. Rf1 Qxe4+ 7. Be2 Nf3#
b) C50 Italian Game: Schilling-Kostic Gambit 1. e4 e5 2. Nf3 Nc6 3. Bc4 Nd4

I believe the legend behind this is that Blackburne played games for a shilling using this line.
Looking around the web, it sounds like in version b), "Schilling" comes from a misunderstanding that "shilling" was a name.
Borislav Kostić was apparently the person who actually played the line in recorded games.

If this is accurate, either "Blackburne Shilling-Kostić", or "Blackburne-Kostić", or "Kostić" would make sense as the name for b), and likely the middle one strikes the right balance between accuracy and common usage.

Also note the name is spelled Kostić, not Kostic.

A separate issue is whether the current a) entry makes sense as an inclusion in the opening database given it's a full game and a "mainline" extension of b)?

If it should be kept, it would sound like a) should be classified along the lines of: "Italian Game: Blackburne-Kostić Gambit, Blackburne Shilling Variation" to make it consistent.

**Therefore I would propose** to change the names as follows: 
a) to "Italian Game: Blackburne-Kostić Gambit, Blackburne Shilling Variation"
b) to "Italian Game: Blackburne-Kostić Gambit"

Relevant wikiepedia entry: https://en.wikipedia.org/wiki/Blackburne_Shilling_Gambit

**Comment by niklasf** [comment]
Thanks! I have removed (a), adjusted (b) as you recommended, and fixed the spelling of Kostić in one other entry.

**Comment by kubafast** [comment]
Thanks so much, appreciated!
I have a few other observations, I will try to submit as PRs so it's less hassle for you.
