### ISSUE TITLE
Datasets have multiple duplicate lines

### ISSUE THREAD

**Issue by hitansh1299** [lichess-org/chess-openings#62]
The datasets have multiple duplicate lines in them. Take for eg [L30 and L31 in the b.tsv](https://github.com/lichess-org/chess-openings/blob/master/b.tsv#L30). I'd assume this pollutes the db. I suggest adding a python script to remove duplicate lines, lines where all the ECO, full name and the PGN is the same, that runs when you make. I'd be happy to create a PR if it makes sense.

**Comment by fynsta** [comment]
It's not entirely the same... One has 3. Nc3, the other one has 3. Nf3

**Comment by niklasf** [comment]
The script you suggest is already part of CI, too.

**Comment by hitansh1299** [comment]
Fair enough, that was an oversight, thanks!
