### ISSUE TITLE
What is the publish workflow for?

### ISSUE THREAD

**Issue by SandroMartens** [lichess-org/chess-openings#89]
Everytime I sync the commits from the lichess branch in my personal branch I get an mail saying something went wrong? But I dont know what this is

![image](https://user-images.githubusercontent.com/66642986/210016970-c4f3b1ca-c4ce-447d-99be-b49ce2e9fd20.png)
![image](https://user-images.githubusercontent.com/66642986/210017146-1961bfd9-e64d-4000-b423-cce7d153e6fe.png)

**Comment by niklasf** [comment]
This was used to publish the `.tsv` files with some additional columns, for ease of use, but it doesn't work in forks. Replaced this mechanism with release artifact uploads that should work anywhere.
